---
minVersion: '0.9.1'
github:
  owner: getsentry
  repo: sentry-electron
changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
statusProvider:
  name: github
targets:
  - name: npm
  - name: registry
    type: sdk
    config:
      canonical: 'npm:@sentry/electron'
  - name: github
