name: 'Build & Test'
on:
  push:
    branches:
      - master
      - release/**
  pull_request:

env:
  ELECTRON_CACHE_DIR: ${{ github.workspace }}

jobs:
  job_1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            .cache/**
            **/node_modules
          key: ${{ runner.os }}-${{ github.sha }}
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Pack
        run: yarn pack
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/*.tgz

  job_2:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            .cache/**
            **/node_modules
          key: ${{ runner.os }}-${{ github.sha }}
      - run: yarn install
      - name: Run Linter
        run: yarn lint

  job_3:
    name: Unit Tests
    needs: job_1
    runs-on: ${{ matrix.os }}
    strategy:
      # we want that the matrix keeps running, default is to cancel them if it fails.
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            .cache/**
            **/node_modules
          key: ${{ runner.os }}-${{ github.sha }}
      - run: yarn install
      - name: Run Unit Tests
        run: yarn test

  job_4:
    name: E2E Tests
    needs: job_1
    runs-on: ${{ matrix.os }}
    strategy:
      # we want that the matrix keeps running, default is to cancel them if it fails.
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            .cache/**
            **/node_modules
          key: ${{ runner.os }}-${{ github.sha }}
      - run: yarn install
      - name: Run E2E Tests
        run: yarn e2e
